p8105\_hw3\_TZ2472
================
tianwei zhao
10/12/2021

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

The goal is to do some exploration of this dataset. To that end, write a
short description of the dataset, noting the size and structure of the
data, describing some key variables, and giving illstrative examples of
observations. Then, do or answer the following (commenting on the
results of each):

``` r
library(p8105.datasets)
data("instacart")


#an illustrative example of the first order:
instacart %>% 
  filter(order_id%in%  "1")
```

    ## # A tibble: 8 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1        1      49302                 1         1  112108 train               4
    ## 2        1      11109                 2         1  112108 train               4
    ## 3        1      10246                 3         0  112108 train               4
    ## 4        1      49683                 4         0  112108 train               4
    ## 5        1      43633                 5         1  112108 train               4
    ## 6        1      13176                 6         0  112108 train               4
    ## 7        1      47209                 7         0  112108 train               4
    ## 8        1      22035                 8         1  112108 train               4
    ## # … with 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

In the instacart data set, we have a total of 1384617 observations, each
represents an order in instacart .The data has 15 variables, collects
key information about instacart such as : order identifier, product
identifier, order in which each product was added to cart, reordered
records, customer identifier, the order sequence number for usesr, the
day of the week on which the order was placed, the hour of the day on
which the order was placed, days since the last order, name of the
product, aisle identifier,department identifier, name of the aisle, name
of the department.

Take example of the first order of instacart,On Thursday 10 o’clock, an
user ID 112108 check out 8 items that are Bulgarian Yogurt, Organic 4%
Milk Fat Whole Milk Cottage Cheese, Organic Celery Hearts, Cucumber
Kirby, Lightly Smoked Sardines in Olive Oil, Bag of Organic Bananas,
Organic Hass Avocado, Organic Whole String Cheese(exactly in this
order).Those items are in aisle of yogurt,other creams cheeses,fresh
vegetables,fresh vegetables,canned meat seafood,fresh fruits, fresh
fruits,and packaged cheese.It has been 9 days since the user 112108’s
last order.Among the orders, Bulgarian Yogurt, Organic 4% Milk Fat Whole
Milk Cottage Cheese,Lightly Smoked Sardines in Olive Oil,Organic Whole
String Cheese are ordered before, and the rest are new tries to this
user.

How many aisles are there, and which aisles are the most items ordered
from?

``` r
instacart %>% 
  count(aisle,aisle_id) %>% 
  arrange(desc(n))
```

    ## # A tibble: 134 × 3
    ##    aisle                         aisle_id      n
    ##    <chr>                            <int>  <int>
    ##  1 fresh vegetables                    83 150609
    ##  2 fresh fruits                        24 150473
    ##  3 packaged vegetables fruits         123  78493
    ##  4 yogurt                             120  55240
    ##  5 packaged cheese                     21  41699
    ##  6 water seltzer sparkling water      115  36617
    ##  7 milk                                84  32644
    ##  8 chips pretzels                     107  31269
    ##  9 soy lactosefree                     91  26240
    ## 10 bread                              112  23635
    ## # … with 124 more rows

The result data set(134\*3) gives us the most ordered items in the first
row,from the table we can find there are 134 aisles and the fresh
vegetables is the most items ordered from.

Make a plot that shows the number of items ordered in each aisle,
limiting this to aisles with more than 10000 items ordered. Arrange
aisles sensibly, and organize your plot so others can read it.

``` r
  instacart %>% 
  count(aisle) %>% 
  arrange(n) %>% 
  filter(n>10000) %>% 
  mutate(
    aisle = factor(aisle),
    aisle = forcats::fct_reorder(aisle, sort(n))) %>% 
  ggplot(aes(x=n,y=aisle,color = n))+
  geom_point()+
  labs(
    title = "Number of items ordered in Insta's aisles plot",
    x = "Number of items ordered",
    y = "Aisle",
    caption = "Data from the instacart"
  )+
  scale_x_continuous(
    breaks = c(0,20000,40000,60000,80000,100000,120000,140000)
  )
```

![](p8105_hw3_TZ2472_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

I arrange the aisles in a increasing order of number of items ordered
for better readability, and use color function to denote the difference
of number of items ordered.The lighter the color is , the more the item
ordered.

Make a table showing the three most popular items in each of the aisles
“baking ingredients”, “dog food care”, and “packaged vegetables fruits”.
Include the number of times each item is ordered in your table.

``` r
new_df = instacart %>% 
  filter(aisle%in%c("baking ingredients", "dog food care","packaged vegetables fruits")) %>% 
  group_by(product_name,aisle) %>% 
  summarize(n_obs=n())
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

``` r
baking_df = 
  filter(new_df,aisle%in% "baking ingredients") %>% 
  arrange(desc(n_obs)) %>% 
  filter(n_obs> 330)

dog_df = 
  filter(new_df,aisle%in% "dog food care") %>% 
  arrange(desc(n_obs)) %>% 
  filter(n_obs> 25)

vegfruit_df = 
  filter(new_df,aisle%in% "packaged vegetables fruits") %>% 
  arrange(desc(n_obs)) %>% 
  filter(n_obs> 4060)

top3_table = 
  bind_rows(baking_df,dog_df,vegfruit_df) %>% 
  relocate(aisle) %>% 
  rename(num_of_time_ordered = n_obs) %>% 
  knitr::kable(caption = "TOP3 Popular Items")

top3_table
```

| aisle                      | product\_name                                 | num\_of\_time\_ordered |
|:---------------------------|:----------------------------------------------|-----------------------:|
| baking ingredients         | Light Brown Sugar                             |                    499 |
| baking ingredients         | Pure Baking Soda                              |                    387 |
| baking ingredients         | Cane Sugar                                    |                    336 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |                     30 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |                     28 |
| dog food care              | Small Dog Biscuits                            |                     26 |
| packaged vegetables fruits | Organic Baby Spinach                          |                   9784 |
| packaged vegetables fruits | Organic Raspberries                           |                   5546 |
| packaged vegetables fruits | Organic Blueberries                           |                   4966 |

TOP3 Popular Items

In the table top3\_table, it contains the top 3 popular items’ names and
number of times ordered in baking ingredients aisle, dog food care
aisle, and packaged vegetables fruits aisle.

Make a table showing the mean hour of the day at which Pink Lady Apples
and Coffee Ice Cream are ordered on each day of the week; format this
table for human readers (i.e. produce a 2 x 7 table).

``` r
pinkapple_df = instacart %>% 
  filter(product_name%in%c("Pink Lady Apples","Coffee Ice Cream"))%>% 
  group_by(order_dow,product_name) %>% 
  summarize(
    mean_hour = mean(order_hour_of_day)) %>% 
  pivot_wider(
    names_from = "order_dow",
    values_from = "mean_hour",
  ) %>% 
  rename("Sunday" = "0", 
         "Monday" = "1", 
         "Tuesday" = "2", 
         "Wednesday" = "3",
         "Thursday" = "4",
         "Friday" = "5",
         "Saturday" = "6") %>% 
  knitr::kable(caption = "Mean Hour on Each Day of the Week")
```

    ## `summarise()` has grouped output by 'order_dow'. You can override using the `.groups` argument.

``` r
pinkapple_df
```

| product\_name    |   Sunday |   Monday |  Tuesday | Wednesday | Thursday |   Friday | Saturday |
|:-----------------|---------:|---------:|---------:|----------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 |  15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 |  14.25000 | 11.55172 | 12.78431 | 11.93750 |

Mean Hour on Each Day of the Week

This table shows the mean hour of the day at which Pink Lady Apples and
Coffee Ice Cream are ordered on each day of the week. The mean hour of
the day that people order Pink Lady Apples and Coffee Ice Cream is
around 11 o’clock and 14 o’clock. The mean varies very slightly in each
day of the week.

\#\#Problem 2

``` r
library(p8105.datasets)
data("brfss_smart2010")
```

First, do some data cleaning:

format the data to use appropriate variable names; focus on the “Overall
Health” topic include only responses from “Excellent” to “Poor” organize
responses as a factor taking levels ordered from “Poor” to “Excellent”

``` r
mydata_df=brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  rename(
    state = locationabbr,
    location = locationdesc
  ) %>% 
  filter(topic%in%"Overall Health",
         response%in% c("Excellent","Very good","Good","Fair","Poor")) %>% 
  relocate(topic,response) %>% 
  mutate(
    response = factor(response),
    response = forcats::fct_relevel(response,c("Poor","Fair","Good","Very good","Excellent"))
  ) %>% 
  arrange(response)
mydata_df
```

    ## # A tibble: 10,625 × 23
    ##    topic          response  year state location class question sample_size data_value
    ##    <chr>          <fct>    <int> <chr> <chr>    <chr> <chr>          <int>      <dbl>
    ##  1 Overall Health Poor      2010 AL    AL - Je… Heal… How is …          45        5.5
    ##  2 Overall Health Poor      2010 AL    AL - Mo… Heal… How is …          66        6.4
    ##  3 Overall Health Poor      2010 AL    AL - Tu… Heal… How is …          35        4.2
    ##  4 Overall Health Poor      2010 AZ    AZ - Ma… Heal… How is …          62        3.5
    ##  5 Overall Health Poor      2010 AZ    AZ - Pi… Heal… How is …          49        5.7
    ##  6 Overall Health Poor      2010 AZ    AZ - Pi… Heal… How is …          30        4  
    ##  7 Overall Health Poor      2010 AR    AR - Be… Heal… How is …          21        3  
    ##  8 Overall Health Poor      2010 AR    AR - Pu… Heal… How is …          36        3.8
    ##  9 Overall Health Poor      2010 AR    AR - Wa… Heal… How is …          16        2.4
    ## 10 Overall Health Poor      2010 CA    CA - Al… Heal… How is …          23        2.4
    ## # … with 10,615 more rows, and 14 more variables: confidence_limit_low <dbl>,
    ## #   confidence_limit_high <dbl>, display_order <int>, data_value_unit <chr>,
    ## #   data_value_type <chr>, data_value_footnote_symbol <chr>,
    ## #   data_value_footnote <chr>, data_source <chr>, class_id <chr>,
    ## #   topic_id <chr>, location_id <chr>, question_id <chr>, respid <chr>,
    ## #   geo_location <chr>

Using this dataset, do or answer the following (commenting on the
results of each):

In 2002, which states were observed at 7 or more locations? What about
in 2010?

``` r
mydata_df %>% 
  filter(year == 2002) %>% 
  group_by(state) %>%
  summarize(n_obs=n_distinct(location)) %>% 
  filter(n_obs>=7) %>% 
  select(state)
```

    ## # A tibble: 6 × 1
    ##   state
    ##   <chr>
    ## 1 CT   
    ## 2 FL   
    ## 3 MA   
    ## 4 NC   
    ## 5 NJ   
    ## 6 PA

``` r
mydata_df %>% 
  filter(year == 2010) %>% 
  group_by(state) %>%
  summarize(n_obs=n_distinct(location)) %>% 
  filter(n_obs>=7) %>% 
  select(state)
```

    ## # A tibble: 14 × 1
    ##    state
    ##    <chr>
    ##  1 CA   
    ##  2 CO   
    ##  3 FL   
    ##  4 MA   
    ##  5 MD   
    ##  6 NC   
    ##  7 NE   
    ##  8 NJ   
    ##  9 NY   
    ## 10 OH   
    ## 11 PA   
    ## 12 SC   
    ## 13 TX   
    ## 14 WA

In 2002, there are 6 states that were observed at 7 or more locations.
Those states are CT,FL,MA, NC, NJ, and PA.

In 2010, there are 14 states that were observed at 7 or more locations.
Those states are CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, and
WA.

Construct a dataset that is limited to Excellent responses, and
contains, year, state, and a variable that averages the data\_value
across locations within a state. Make a “spaghetti” plot of this average
value over time within a state (that is, make a plot showing a line for
each state across years – the geom\_line geometry and group aesthetic
will help).

``` r
mydata_df %>% 
  filter(response == "Excellent") %>% 
  group_by(year,state) %>% 
  mutate(mean_data_value = mean(data_value,rm.na=TRUE)) %>% 
  select(year,state,mean_data_value) %>% 
  ggplot(aes(x = year,y = mean_data_value,color = state))+
  geom_line(aes(group = state))+
  theme(legend.position = "right")
```

    ## Warning: Removed 65 row(s) containing missing values (geom_path).

![](p8105_hw3_TZ2472_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

Make a two-panel plot showing, for the years 2006, and 2010,
distribution of data\_value for responses (“Poor” to “Excellent”) among
locations in NY State.

``` r
mydata_df %>% 
  filter(year%in%c(2006,2009),
         state == "NY") %>% 
  ggplot(aes(x = data_value, fill = response)) +
  geom_density(alpha = .5) + 
  facet_grid(. ~ year) +
  theme(legend.position = "bottom")
```

![](p8105_hw3_TZ2472_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

## Problem 3

Load, tidy, and otherwise wrangle the data. Your final dataset should
include all originally observed variables and values; have useful
variable names; include a weekday vs weekend variable; and encode data
with reasonable variable classes. Describe the resulting dataset
(e.g. what variables exist, how many observations, etc).

``` r
accel_df = read_csv("accel_data.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
   "activity_1":"activity_1440",
    names_to = "activity_order",
    names_prefix = "activity_",
    values_to = "activity") %>% 
  rename(activity_counts = activity) %>% 
  mutate(
    day_type = if_else(day %in% c("Saturday","Sunday"), "weekend","weekday"),
    week = as.integer(week),
    day_id = as.integer(day_id),
    activity_order = as.integer(activity_order)
          ) %>% 
  select(week,day_id,day, day_type,activity_order,activity_counts)
```

    ## Rows: 35 Columns: 1443

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This data set have 6 variables, including the week, day, day\_id, minute
of the day, day\_type, and activity value. The set has 50400
observations. Each observation is about the activity counts for a
specific minute from a 24-hour day and the information about that day,
including the week, day\_id, and whether it is a weekday or weekend.

Traditional analyses of accelerometer data focus on the total activity
over the day. Using your tidied dataset, aggregate accross minutes to
create a total activity variable for each day, and create a table
showing these totals. Are any trends apparent?

``` r
accel_df %>% 
  group_by(day_id) %>% 
  mutate(total_activity = sum(activity_counts)) %>% 
  select(day_id, day, day_type, total_activity) %>% 
  distinct() %>% 
  knitr::kable()
```

| day\_id | day       | day\_type | total\_activity |
|--------:|:----------|:----------|----------------:|
|       1 | Friday    | weekday   |       480542.62 |
|       2 | Monday    | weekday   |        78828.07 |
|       3 | Saturday  | weekend   |       376254.00 |
|       4 | Sunday    | weekend   |       631105.00 |
|       5 | Thursday  | weekday   |       355923.64 |
|       6 | Tuesday   | weekday   |       307094.24 |
|       7 | Wednesday | weekday   |       340115.01 |
|       8 | Friday    | weekday   |       568839.00 |
|       9 | Monday    | weekday   |       295431.00 |
|      10 | Saturday  | weekend   |       607175.00 |
|      11 | Sunday    | weekend   |       422018.00 |
|      12 | Thursday  | weekday   |       474048.00 |
|      13 | Tuesday   | weekday   |       423245.00 |
|      14 | Wednesday | weekday   |       440962.00 |
|      15 | Friday    | weekday   |       467420.00 |
|      16 | Monday    | weekday   |       685910.00 |
|      17 | Saturday  | weekend   |       382928.00 |
|      18 | Sunday    | weekend   |       467052.00 |
|      19 | Thursday  | weekday   |       371230.00 |
|      20 | Tuesday   | weekday   |       381507.00 |
|      21 | Wednesday | weekday   |       468869.00 |
|      22 | Friday    | weekday   |       154049.00 |
|      23 | Monday    | weekday   |       409450.00 |
|      24 | Saturday  | weekend   |         1440.00 |
|      25 | Sunday    | weekend   |       260617.00 |
|      26 | Thursday  | weekday   |       340291.00 |
|      27 | Tuesday   | weekday   |       319568.00 |
|      28 | Wednesday | weekday   |       434460.00 |
|      29 | Friday    | weekday   |       620860.00 |
|      30 | Monday    | weekday   |       389080.00 |
|      31 | Saturday  | weekend   |         1440.00 |
|      32 | Sunday    | weekend   |       138421.00 |
|      33 | Thursday  | weekday   |       549658.00 |
|      34 | Tuesday   | weekday   |       367824.00 |
|      35 | Wednesday | weekday   |       445366.00 |

No, there is no trends apparent.

Accelerometer data allows the inspection activity over the course of the
day. Make a single-panel plot that shows the 24-hour activity time
courses for each day and use color to indicate day of the week. Describe
in words any patterns or conclusions you can make based on this graph.

``` r
total_activity_df = accel_df %>% 
  group_by(day_id) %>% 
mutate(
    total_activity = sum(activity_counts))

total_activity_df %>% 
  group_by(week) %>% 
  ggplot(aes(x = day_id, y = total_activity, color = day)) + 
  geom_point() +
  geom_line()
```

![](p8105_hw3_TZ2472_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

From the plot we can see that the total activity time for each day
differs significantly from one day to another. Moreover, even for the
same day of the week, the activity time courses are very different week
from week. This is abnormal, suggesting that there might be some mistake
in the original data, especially the recording in Saturday, where the
participants had as high as 607175 counts in week two and as low as 1440
in week 4 and 5. Therefore, we might have to go back to the original
data and correct the data before further analysis.
